[package]
name = "palimp-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
palimp-core = { version = "0.1.0", path = "../palimp-core" }
slint = "1.9.2"
tokio = { version = "1.43.0", features = ["full"] }

[build-dependencies]
slint-build = "1.9.2"
