[package]
name = "palimp-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.4.0"
palimp-core = { version = "0.1.0", path = "../palimp-core" }
tokio = { version = "1", features = ["full"] }
